version: "3.7"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: letmein

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - '8545:8545'

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    environment:
      postgres_host: postgres
      postgres_port: 5432
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: "matic:https://polygon-mainnet.g.alchemy.com/v2/qnUki_B3TXm9I2qW0eQ2neiRGlH71bOG"
      RUST_BACKTRACE: 1
