export enum RequestActivityType {
  INITIALIZE,
  PAUSE,
  UNPAUSE,
  FLAG,
  PROPOSE,
  DISPUTE,
  RESET,
  RESOLVE,
  RESOLVE_MANUALLY,
  NEGRISK_REPORT,
  NEGRISK_RESOLVE,
  NEGRISK_FLAG,
  NEGRISK_UNFLAG,
  NEGRISK_RESOLVE_MANUALLY
} 